apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-sap-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fake-sap-api
  template:
    metadata:
      labels:
        app: fake-sap-api
    spec:
      containers:
        - name: fake-sap-api
          image: stefanbobal/fake-sap-api:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fake-sap-api-config
            - secretRef:
                name: fake-sap-api-secret
